name: ubuntu

on: [ubuntu]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install libcurl
      run: sudo apt-get install libcurl4-openssl-dev
    - name: make
      run: make
  
